#line 1 "main_layout.tmpl"
#include "content.h" 
#line 2 "main_layout.tmpl"
namespace main_layout {
	#line 3 "main_layout.tmpl"
	struct message :public cppcms::base_view
	#line 3 "main_layout.tmpl"
	{
	#line 3 "main_layout.tmpl"
		content::message &content;
	#line 3 "main_layout.tmpl"
		message(std::ostream &_s,content::message &_content): cppcms::base_view(_s),content(_content)
	#line 3 "main_layout.tmpl"
		{
	#line 3 "main_layout.tmpl"
		}
		#line 4 "main_layout.tmpl"
		virtual void render() {
			#line 452 "main_layout.tmpl"
			out()<<" \n"
				"  <!doctype html>\n"
				"  <!--[if IE 7 ]>    <html lang=\"en-gb\" class=\"isie ie7 oldie no-js\"> <![endif]-->\n"
				"  <!--[if IE 8 ]>    <html lang=\"en-gb\" class=\"isie ie8 oldie no-js\"> <![endif]-->\n"
				"  <!--[if IE 9 ]>    <html lang=\"en-gb\" class=\"isie ie9 no-js\"> <![endif]-->\n"
				"  <!--[if (gt IE 9)|!(IE)]><!--> <html lang=\"en-gb\" class=\"no-js\"> <!--<![endif]-->\n"
				"\n"
				"  <head>\n"
				"    <title>Portfolio devices slider | KALLYAS Template</title>\n"
				"    \n"
				"    <meta charset=\"utf-8\">\n"
				"    <meta name=\"keywords\" content=\"premium html template, unique premium template, multipurpose\" />\n"
				"    <meta name=\"description\" content=\"Welcome to KALLYAS Template, a wonderful and premium product for multipurpose websites\" />\n"
				"\n"
				"    <link rel=\"stylesheet\" href=\"css/bootstrap.css\" type=\"text/css\" />\n"
				"    <link rel=\"stylesheet\" href=\"addons/superfish_responsive/superfish.css\" type=\"text/css\" />\n"
				"    <link rel=\"stylesheet\" href=\"css/template.css\" type=\"text/css\" />\n"
				"    <link rel=\"stylesheet\" href=\"css/updates.css\" type=\"text/css\" />\n"
				"    <link rel=\"stylesheet\" href=\"css/custom.css\" type=\"text/css\" />\n"
				"\n"
				"    \n"
				"    <!-- This stylesheet only adds some repairs on idevices  -->\n"
				"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
				"\n"
				"    <link rel=\"stylesheet\" href=\"css/responsive-devices.css\" type=\"text/css\" />\n"
				"    \n"
				"    <link rel=\"stylesheet\" href=\"http://fonts.googleapis.com/css?family=Lato:300,400,700,900&amp;v1&mp;subset=latin,latin-ext\" type=\"text/css\" media=\"screen\" id=\"google_font\" />\n"
				"    <link rel=\"stylesheet\" href=\"http://fonts.googleapis.com/css?family=Open+Sans:400,400italic,700&amp;v1&mp;subset=latin,latin-ext\" type=\"text/css\" media=\"screen\" id=\"google_font_body\" />\n"
				"    \n"
				"    <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->\n"
				"    <script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js\"></script>\n"
				"    <script>window.jQuery || document.write('<script src=\"js/jquery-1.8.2.min.js\">\\x3C/script>')</script>\n"
				"    <script src=\"js/jquery.noconflict.js\" type=\"text/javascript\"></script>\n"
				"    <script src=\"http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.6.1/modernizr.min.js\" type=\"text/javascript\"></script>\n"
				"    \n"
				"    <link rel=\"shortcut icon\" href=\"images/favicons/favicon.png\">\n"
				"    <link rel=\"apple-touch-icon\" href=\"images/favicons/apple-touch-icon-57x57.png\">\n"
				"    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"images/favicons/apple-touch-icon-72x72.png\">\n"
				"    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"images/favicons/apple-touch-icon-114x114.png\">\n"
				"    \n"
				"    <!--[if lte IE 9]>\n"
				"      <link rel=\"stylesheet\" type=\"text/css\" href=\"css/fixes.css\" />\n"
				"    <![endif]-->\n"
				"\n"
				"    <!--[if lte IE 8]>\n"
				"      <script src=\"js/respond.js\"></script>\n"
				"      <script type=\"text/javascript\"> \n"
				"      var $buoop = {vs:{i:8,f:6,o:10.6,s:4,n:9}} \n"
				"      $buoop.ol = window.onload; \n"
				"      window.onload=function(){ \n"
				"       try {if ($buoop.ol) $buoop.ol();}catch (e) {} \n"
				"       var e = document.createElement(\"script\"); \n"
				"       e.setAttribute(\"type\", \"text/javascript\"); \n"
				"       e.setAttribute(\"src\", \"http://browser-update.org/update.js\"); \n"
				"       document.body.appendChild(e); \n"
				"      } \n"
				"      </script> \n"
				"    <![endif]-->\n"
				"    \n"
				"    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->\n"
				"    <!--[if lt IE 9]>\n"
				"      <script src=\"http://html5shim.googlecode.com/svn/trunk/html5.js\"></script>\n"
				"    <![endif]-->\n"
				"    \n"
				"    <!-- Facebook OpenGraph Tags - Replace with your own -->\n"
				"    <meta property=\"og:title\" content=\"KALLYAS Template HTML\"/>\n"
				"    <meta property=\"og:type\" content=\"website\"/>\n"
				"    <meta property=\"og:url\" content=\"http://www.hogash.com/demo/kalypso_html/\"/>\n"
				"    <meta property=\"og:image\" content=\"http://www.hogash.com/demo/kalypso_html/images/logo.png\"/>\n"
				"    <meta property=\"og:site_name\" content=\"Kallyas\"/>\n"
				"    <meta property=\"fb:app_id\" content=\"\"/> <!-- PUT HERE YOUR OWN APP ID - you could get errors if you don't use this one -->\n"
				"    <meta property=\"og:description\" content=\"Welcome to KALLYAS Template, a wonderful and premium product for multipurpose websites\"/>\n"
				"    <!-- END Facebook OpenGraph Tags -->\n"
				"    \n"
				"    <!-- THIS IS THE DARK THEME STYLESEET // REMOVE COMMENTS TO ENABLE -->\n"
				"    <!-- <link rel=\"stylesheet\" href=\"css/dark-theme.css\" type=\"text/css\" /> -->\n"
				"    <!-- END DARK THEME -->\n"
				"      <!-- REVOLUTION BANNER CSS SETTINGS -->\n"
				"      \n"
				"    <style type=\"text/css\">\n"
				"    html { overflow-x:hidden; padding: 0 !important; margin:0px !important; }\n"
				"     .fullwidthbanner-container{ width:100% !important; position:relative; padding:0; max-height:600px !important; overflow:hidden;  }\n"
				"    </style>\n"
				"    <link rel=\"stylesheet\" type=\"text/css\" href=\"sliders/revolution_slider/css/settings.css\" media=\"screen\" />\n"
				"      <link rel=\"stylesheet\" type=\"text/css\" href=\"sliders/revolution_slider/css/portfolio_devices.css\" media=\"screen\" />\n"
				"  </head>\n"
				"\n"
				"  <body class=\"\">\n"
				"\n"
				"        <!-- ADD AN APPLICATION ID !!\n"
				"    If you want to know how to find out your app id, either search on google for: facebook appid, either go to http://rieglerova.net/how-to-get-a-facebook-app-id/ -->\n"
				"    <div id=\"fb-root\"></div>\n"
				"    <script>(function(d, s, id) {\n"
				"    var js, fjs = d.getElementsByTagName(s)[0];\n"
				"    if (d.getElementById(id)) return;\n"
				"    js = d.createElement(s); js.id = id;\n"
				"    js.src = \"http://connect.facebook.net/en_US/all.js#xfbml=1&appId=\"; // addyour appId here\n"
				"    fjs.parentNode.insertBefore(js, fjs);\n"
				"    }(document, 'script', 'facebook-jssdk'));</script>\n"
				"      \n"
				"        <div class=\"support_panel\" id=\"sliding_panel\">\n"
				"      <div class=\"container\">\n"
				"        <div class=\"row\">\n"
				"          <div class=\"span9\">\n"
				"            <h4 class=\"m_title\">HOW TO SHOP</h4>\n"
				"            <div class=\"m_content how_to_shop\">\n"
				"              <div class=\"row\">\n"
				"                <div class=\"span3\">\n"
				"                  <span class=\"number\">1</span> Login or create new account.\n"
				"                </div>\n"
				"                <div class=\"span3\">\n"
				"                  <span class=\"number\">2</span> Review your order.\n"
				"                </div>\n"
				"                <div class=\"span3\">\n"
				"                  <span class=\"number\">3</span> Payment &amp; <strong>FREE</strong> shipment\n"
				"                </div>\n"
				"              </div>\n"
				"              <p>If you still have problems, please let us know, by sending an email to support@website.com . Thank you!</p>\n"
				"            </div><!-- end how to shop steps -->\n"
				"          </div>\n"
				"          <div class=\"span3\">\n"
				"            <h4 class=\"m_title\">SHOWROOM HOURS</h4>\n"
				"            <div class=\"m_content\">\n"
				"            Mon-Fri 9:00AM - 6:00AM<br>\n"
				"            Sat - 9:00AM-5:00PM<br>\n"
				"            Sundays by appointment only!\n"
				"            </div>\n"
				"          </div>\n"
				"        </div>\n"
				"      </div>\n"
				"    </div><!-- end support panel -->\n"
				"      \n"
				"    <div class=\"login_register_stuff hide\"><!-- Login/Register Modal forms - hidded by default to be opened through modal -->\n"
				"      <div id=\"login_panel\">\n"
				"        <div class=\"inner-container login-panel\">\n"
				"          <h3 class=\"m_title\">SIGN IN YOUR ACCOUNT TO HAVE ACCESS TO DIFFERENT FEATURES</h3>\n"
				"          <form id=\"login_form\" name=\"login_form\" method=\"post\">\n"
				"            <a href=\"#\" class=\"create_account\" onClick=\"ppOpen('#register_panel', '280');\">CREATE ACCOUNT</a>\n"
				"            <input type=\"text\" id=\"username\" name=\"username\" class=\"inputbox\" placeholder=\"Username\">\n"
				"            <input type=\"password\" id=\"password\" name=\"password\" class=\"inputbox\" placeholder=\"Password\">\n"
				"            <input type=\"submit\" id=\"login\" name=\"submit\" value=\"LOG IN\">\n"
				"            <a href=\"#\" class=\"login_facebook\">login with facebook</a>\n"
				"          </form>\n"
				"          <div class=\"links\"><a href=\"#\" onClick=\"ppOpen('#forgot_panel', '350');\">FORGOT YOUR USERNAME?</a> / <a href=\"#\" onClick=\"ppOpen('#forgot_panel', '350');\">FORGOT YOUR PASSWORD?</a></div>\n"
				"        </div>\n"
				"      </div><!-- end login panel -->\n"
				"\n"
				"      <div id=\"register_panel\">\n"
				"        <div class=\"inner-container register-panel\">\n"
				"          <h3 class=\"m_title\">CREATE ACCOUNT</h3>\n"
				"          <form id=\"register_form\" name=\"register_form\" method=\"post\">\n"
				"            <p>\n"
				"              <input type=\"text\" id=\"reg-username\" name=\"username\" class=\"inputbox\" placeholder=\"Username\">\n"
				"            </p>\n"
				"            <p>\n"
				"              <input type=\"text\" id=\"fullname\" name=\"fullname\" class=\"inputbox\" placeholder=\"Your full name\">\n"
				"            </p>\n"
				"            <p>\n"
				"              <input type=\"text\" id=\"reg-email\" name=\"email\" class=\"inputbox\" placeholder=\"Your email\">\n"
				"            </p>\n"
				"                      <p>\n"
				"              <input type=\"password\" id=\"reg-password\" name=\"password\" class=\"inputbox\" placeholder=\"Desired password\">\n"
				"            </p>\n"
				"            <p>\n"
				"              <input type=\"password\" id=\"confirm_password\" name=\"confirm_password\" class=\"inputbox\" placeholder=\"Confirm password\">\n"
				"            </p>\n"
				"            <p>\n"
				"              <input type=\"submit\" id=\"signup\" name=\"submit\" value=\"CREATE MY ACCOUNT\">\n"
				"            </p>\n"
				"          </form>\n"
				"          <div class=\"links\"><a href=\"#\" onClick=\"ppOpen('#login_panel', '800');\">ALREADY HAVE AN ACCOUNT?</a></div>\n"
				"        </div>\n"
				"      </div><!-- end register panel -->\n"
				"\n"
				"      <div id=\"forgot_panel\">\n"
				"        <div class=\"inner-container forgot-panel\">\n"
				"          <h3 class=\"m_title\">FORGOT YOUR DETAILS?</h3>\n"
				"          <form id=\"forgot_form\" name=\"forgot_form\" method=\"post\">\n"
				"            <p>\n"
				"              <input type=\"text\" id=\"forgot-email\" name=\"email\" class=\"inputbox\" placeholder=\"Email Address\">\n"
				"            </p>\n"
				"            <p>\n"
				"              <input type=\"submit\" id=\"recover\" name=\"submit\" value=\"SEND MY DETAILS!\">\n"
				"            </p>\n"
				"          </form>\n"
				"          <div class=\"links\"><a href=\"#\" onClick=\"ppOpen('#login_panel', '800');\">AAH, WAIT, I REMEMBER NOW!</a></div>\n"
				"        </div>\n"
				"      </div><!-- end register panel -->\n"
				"    </div><!-- end login register stuff -->\n"
				"      \n"
				"    <div id=\"page_wrapper\">\n"
				"\n"
				"      <header id=\"header\" class=\"style2\">\n"
				"        <div class=\"container\">\n"
				"\n"
				"          <!-- logo -->\n"
				"          <h1 id=\"logo\"><a href=\"index.html\"><img src=\"images/logo.png\" alt=\"Kallyas HTML Template\"></a></h1>\n"
				"\n"
				"          <ul class=\"topnav navRight\">\n"
				"            <li><a href=\"#\" id=\"open_sliding_panel\">\n"
				"                <span class=\"icon-remove-circle icon-white\"></span> SUPPORT\n"
				"              </a>\n"
				"            </li>\n"
				"            <li><a href=\"#login_panel\" data-rel=\"prettyPhoto[login_panel]\">LOGIN</a></li>\n"
				"          </ul><!-- end topnav // right aligned -->\n"
				"\n"
				"          <ul class=\"topnav navLeft\">\n"
				"            <li class=\"drop\"><a href=\"#\">MY CART</a>\n"
				"              <div class=\"pPanel\">\n"
				"                <div class=\"inner\">\n"
				"                  <span class=\"cart_details\">3 items, Total of <strong>$599 USD</strong> <a href=\"#\" class=\"checkout\">Checkout <span class=\"icon-chevron-right\"></span></a></span>\n"
				"                </div>\n"
				"              </div>\n"
				"            </li>\n"
				"            <li class=\"languages drop\"><a href=\"#\"><span class=\"icon-globe icon-white\"></span> LANGUAGES</a>\n"
				"              <div class=\"pPanel\">\n"
				"                <ul class=\"inner\">\n"
				"                  <li class=\"active\"><a href=\"#\">English <span class=\"icon-ok\"></span></a></li>\n"
				"                  <li><a href=\"#\">French</a></li>\n"
				"                  <li><a href=\"#\">German</a></li>\n"
				"                </ul>\n"
				"              </div>\n"
				"            </li>\n"
				"          </ul><!-- end topnav // left aligned -->\n"
				"\n"
				"          <!-- search -->\n"
				"          <div id=\"search\">\n"
				"            <a href=\"#\" class=\"searchBtn\"><span class=\"icon-search icon-white\"></span></a>\n"
				"            <div class=\"search\">\n"
				"              <form action=\"http://www.google.com/search\" method=\"get\" onSubmit=\"Gsitesearch(this)\" target=\"_blank\">\n"
				"                <input name=\"q\" type=\"hidden\" />\n"
				"                <input name=\"qfront\" maxlength=\"20\" class=\"inputbox\" type=\"text\" size=\"20\" value=\"SEARCH ...\" onblur=\"if (this.value=='') this.value='SEARCH ...';\" onfocus=\"if (this.value=='SEARCH ...') this.value='';\" />\n"
				"                <input type=\"submit\" value=\"go\" class=\"button icon-search\"/>\n"
				"              </form>\n"
				"            </div>\n"
				"          </div><!-- end search -->\n"
				"                  \n"
				"  <script type=\"text/javascript\">\n"
				"  // THIS SCRIPT DETECTS THE ACTIVE ELEMENT AND ADDS ACTIVE CLASS\n"
				"  (function($){ \n"
				"    $(document).ready(function(){\n"
				"      var pathname = window.location.pathname,\n"
				"        page = pathname.split(/[/ ]+/).pop(),\n"
				"        menuItems = $('#main_menu a');\n"
				"      menuItems.each(function(){\n"
				"        var mi = $(this),\n"
				"          miHrefs = mi.attr(\"href\"),\n"
				"          miParents = mi.parents('li');\n"
				"        if(page == miHrefs) {\n"
				"          miParents.addClass(\"active\").siblings().removeClass('active');\n"
				"        }\n"
				"      });\n"
				"    });\n"
				"  })(jQuery);\n"
				"  </script>\n"
				"          <nav id=\"main_menu\">\n"
				"            <ul class=\"sf-menu clearfix\">\n"
				"              <li class=\"active\"><a href=\"index.html\">HOME</a>\n"
				"                <ul>\n"
				"                  <li><a href=\"homepage2.html\">Homepage 2</a></li>\n"
				"                  <li><a href=\"homepage3.html\">Homepage 3</a></li>\n"
				"                  <li><a href=\"homepage4.html\">Homepage 4</a></li>\n"
				"                  <li><a href=\"homepage5.html\">Homepage 5</a></li>\n"
				"                  <li><a href=\"homepage6.html\">Homepage 6</a></li>\n"
				"                  <li><a href=\"homepage-all.html\">Homepage All</a></li>\n"
				"                </ul>\n"
				"              </li>\n"
				"              <li><a href=\"#\">SLIDERS</a>\n"
				"                <ul>\n"
				"                  <li><a href=\"#\">Main Slider</a>\n"
				"                    <ul>\n"
				"                      <li><a href=\"index.html\">Default Style</a></li>\n"
				"                      <li><a href=\"slider-main-with-thumbs.html\">With Thumbs</a></li>\n"
				"                      <li><a href=\"slider-main-faded.html\">Faded</a></li>\n"
				"                      <li><a href=\"slider-main-fixed.html\">Fixed Width Slider</a></li>\n"
				"                      <li><a href=\"slider-main-fixed-position.html\">Fixed Position (Scroll)</a></li>\n"
				"                    </ul>\n"
				"                  </li>\n"
				"                  <li><a href=\"slider-fixed-flexslider.html\">Fixed Slider</a>\n"
				"                    <ul>\n"
				"                      <li><a href=\"slider-fixed-flexslider.html\">Style 1 (Flex Slider)</a>\n"
				"                        <ul>\n"
				"                          <li><a href=\"slider-fixed-flexslider.html\">Default</a></li>\n"
				"                          <li><a href=\"slider-fixed-flexslider-thumbnails.html\">With thumbnails</a></li>\n"
				"                        </ul>\n"
				"                      </li>\n"
				"                      <li><a href=\"slider-fixed-nivoslider.html\">Style 2 (Nivo Slider)</a></li>\n"
				"                      <li><a href=\"slider-fixed-wowslider-blast.html\">Style 3 (Wow Slider)</a>\n"
				"                        <ul>\n"
				"                          <li><a href=\"slider-fixed-wowslider-blast.html\">Blast Effect</a></li>\n"
				"                          <li><a href=\"slider-fixed-wowslider-blinds.html\">Blinds Effect</a></li>\n"
				"                          <li><a href=\"slider-fixed-wowslider-fly.html\">Fly Effect</a></li>\n"
				"                          <li><a href=\"slider-fixed-wowslider-blur.html\">Blur Effect</a></li>\n"
				"                        </ul>\n"
				"                      </li>\n"
				"                    </ul>\n"
				"                  </li>\n"
				"                  <li><a href=\"slider-3dslider.html\">3D Cute Slider</a></li>\n"
				"                  <li><a href=\"slider-fancy.html\">Fancy Slider</a></li>\n"
				"                  <li><a href=\"slider-creative.html\">Creative Slider</a></li>\n"
				"                  <li><a href=\"slider-circularcontent-default.html\">Circular Content</a>\n"
				"                    <ul>\n"
				"                      <li><a href=\"slider-circularcontent-default.html\">Default Style</a></li>\n"
				"                      <li><a href=\"slider-circularcontent-alternative.html\">Alternative Style</a></li>\n"
				"                    </ul>\n"
				"                  </li>\n"
				"                  <li><a href=\"slider-static-content-default.html\">Static Content</a>\n"
				"                    <ul>\n"
				"                      <li><a href=\"slider-static-content-default.html\">Style 1</a></li>\n"
				"                      <li><a href=\"slider-static-content-boxes.html\">Style 2 / Boxes</a></li>\n"
				"                      <li><a href=\"slider-static-content-video.html\">Style 3 / Video</a></li>\n"
				"                      <li><a href=\"slider-static-content-maps.html\">Style 4 / Maps</a></li>\n"
				"                      <li><a href=\"slider-static-content-textpop.html\">Style 5 / Text pop</a></li>\n"
				"                      <li><a href=\"slider-static-content-zoom.html\">Style 6 / Product Loupe</a></li>\n"
				"                      <li><a href=\"slider-static-content-event-countdown.html\">Style 7 / Event countdown</a></li>\n"
				"                      <li><a href=\"slider-static-content-videobg.html\">Style 8 / Video background</a></li><!-- http://www.teehanlax.com/ -->\n"
				"                      <li><a href=\"slider-static-content-text-login.html\">Style 9 / Text &amp; Login</a></li>\n"
				"                      <li><a href=\"slider-static-content-simple.html\">Style 10 / Simple text</a></li>\n"
				"                    </ul>\n"
				"                  </li>\n"
				"                  <li><a href=\"slider-portfolio-devices.html\">Portfolio Slider Devices</a></li>\n"
				"                  <li><a href=\"slider-portfolio-frames.html\">Portfolio Slider Frames</a>\n"
				"                    <ul>\n"
				"                      <li><a href=\"slider-portfolio-frames.html\">Sliding Vertically</a></li>\n"
				"                      <li><a href=\"slider-portfolio-frames-horizontal.html\">Sliding Horizontally</a></li>\n"
				"                    </ul>\n"
				"                  </li>\n"
				"                  <li><a href=\"slider-laptop.html\">Laptop Slider</a></li>\n"
				"                  <li><a href=\"slider-icarousel.html\">iCarousel</a></li>\n"
				"                  <li><a href=\"slider-css3panels.html\">CSS3 Panels</a></li>\n"
				"                </ul>\n"
				"              </li>\n"
				"              <li><a href=\"about-us.html\">ABOUT US</a></li>\n"
				"              <li><a href=\"#\">FEATURES</a>\n"
				"                <ul>\n"
				"                  <li><a href=\"features-blog.html\">Blog</a></li>\n"
				"                  <li><a href=\"#\">Portfolio</a>\n"
				"                    <ul>\n"
				"                      <li><a href=\"features-portfolio-cat-onecol.html\">Category Layout</a>\n"
				"                        <ul>\n"
				"                          <li><a href=\"features-portfolio-cat-onecol.html\">One Column</a></li>\n"
				"                          <li><a href=\"features-portfolio-cat-twocol.html\">Two Columns</a></li>\n"
				"                          <li><a href=\"features-portfolio-cat-threecol.html\">Three Columns</a></li>\n"
				"                          <li><a href=\"features-portfolio-cat-fourcol.html\">Four Columns</a></li>\n"
				"                        </ul>\n"
				"                      </li>\n"
				"                      <li><a href=\"features-portfolio-sortable.html\">Sortable Layout</a></li>\n"
				"                      <li><a href=\"features-portfolio-carousels.html\">Carousels Layout</a></li>\n"
				"                    </ul>\n"
				"                  </li>\n"
				"                  <li><a href=\"features-photo-gallery.php\">Photo Gallery</a></li>\n"
				"                  <li><a href=\"#\">Lightbox (Prettyphoto)</a>\n"
				"                    <ul>\n"
				"                      <li><a href=\"http://themeforest.net/user/hogash/?iframe=true&amp;width=800&amp;height=450\" data-rel=\"prettyPhoto\">PrettyPhoto (iFrame)</a></li>\n"
				"                      <li><a href=\"images/super_cool_ad.jpg\" data-rel=\"prettyPhoto\">PrettyPhoto (Image)</a></li>\n"
				"                      <li><a href=\"http://www.youtube.com/watch?v=G-1HNnxb0WE\" data-rel=\"prettyPhoto\">PrettyPhoto (Youtube)</a></li>\n"
				"                      <li><a href=\"features-lightbox-autopop.html\">Auto Pop-up</a></li>\n"
				"                      <li><a href=\"#transparent_panel\" class=\"prettyPhoto_transparent\">Transparent modal</a></li>\n"
				"                    </ul>\n"
				"                  </li>\n"
				"                  <li><a href=\"features-grid-positions.html\">Grid Positions</a></li>\n"
				"                  <li><a href=\"features-sitemap.html\">Sitemap</a></li>\n"
				"                  <li><a href=\"#\">Holiday Slides</a>\n"
				"                    <ul>\n"
				"                      <li><a href=\"features-holiday-christmas.html\">Christmas</a></li>\n"
				"                      <li><a href=\"features-holiday-easter.html\">Easter</a></li>\n"
				"                    </ul>\n"
				"                  </li>\n"
				"                  <li><a href=\"features-page-preloader.html\">Page Preloader</a></li>\n"
				"                  <li><a href=\"features-animated-header.html\">Animated Header</a></li>\n"
				"                </ul>\n"
				"              </li>\n"
				"              <li><a href=\"shop.html\">SHOP</a></li>\n"
				"              <li><a href=\"#\">PAGES</a>\n"
				"                <ul>\n"
				"                  <li><a href=\"pages-faq.html\">FAQ</a></li>\n"
				"                  <li><a href=\"pages-process.html\">Process</a></li>\n"
				"                  <li><a href=\"pages-contact.html\">Contact us</a>\n"
				"                    <ul>\n"
				"                      <li><a href=\"pages-contact.html\">Normal page</a></li>\n"
				"                      <li><a href=\"pages-contact-modal.html?iframe=true&amp;height=430\" class=\"prettyPhoto_transparent\">Via modal</a></li>\n"
				"                    </ul>\n"
				"                  </li>\n"
				"                  <li><a href=\"pages-fullwidth.html\">Full width</a></li>\n"
				"                  <li><a href=\"pages-leftsidebar.html\">Left sidebar</a></li>\n"
				"                  <li><a href=\"pages-rightsidebar.html\">Right sidebar</a></li>\n"
				"                  <li><a href=\"pages-offline.html\">Offline / Coming soon</a></li>\n"
				"                  <li><a href=\"pages-historic.html\">Historic / Timeline</a></li>\n"
				"                  <li><a href=\"pages-testimonials.html\">Testimonials</a></li>\n"
				"                  <li><a href=\"pages-404.html\">404 Error</a></li>\n"
				"                  <li><a href=\"pages-team.html\">Team</a></li>\n"
				"                  <li><a href=\"pages-portfolioitem.html\">Portfolio Item</a></li>\n"
				"                  <li><a href=\"pages-blogitem.html\">Blog Item</a></li> \n"
				"                  <li><a href=\"pages-productitem.html\">Product page</a></li>\n"
				"                  <li><a href=\"pages-product-list.html\">Products List/Category</a></li>\n"
				"                  <li><a href=\"pages-services.html\">Services</a></li>\n"
				"                  <li><a href=\"pages-careers.html\">Careers</a></li>\n"
				"                  <li><a href=\"pages-passprotected.html\">Password Protected</a></li>\n"
				"                </ul>\n"
				"              </li>\n"
				"              <li><a href=\"#\">STYLES</a>\n"
				"                <ul>\n"
				"                  <li><a href=\"styles-typography.html\">Typography</a></li>\n"
				"                  <li><a href=\"styles-tables.html\">Table designs</a></li>\n"
				"                  <li><a href=\"styles-buttons.html\">Button designs</a></li>\n"
				"                  <li><a href=\"styles-pricingtables.html\">Pricing tables</a></li>\n"
				"                  <li><a href=\"styles-forms.html\">Form styles</a></li>\n"
				"                  <li><a href=\"styles-tabs.html\">Tabs designs</a></li>\n"
				"                  <li><a href=\"styles-accordion.html\">Accordion Toogles</a></li>\n"
				"                </ul>\n"
				"              </li>\n"
				"            </ul>\n"
				"          </nav><!-- end main_menu -->\n"
				"\n"
				"        </div>\n"
				"      </header>\n"
				"          \n"
				"          <div id=\"slideshow\" class=\"nobg\">\n"
				"          \n"
				"              <div class=\"fullwidthbanner-container portfolio_devices\">\n"
				"                  <div class=\"fullwidthbanner\">\n"
				"                      <ul>\n"
				"\n"
				"                          <li data-transition=\"slideright\">\n"
				"                              <img src=\"images/sliders/portfolio_devices/slide1/slide1.jpg\" alt=\"\">\n"
				"                              \n"
				"                              <div class=\"caption lft project_title\" data-x=\"284\" data-y=\"120\" data-speed=\"300\" data-start=\"700\" data-easing=\"easeOutExpo\">Ammon Template</div>\n"
				"                              <div class=\"caption lft more_details\" data-x=\"410\" data-y=\"155\" data-speed=\"300\" data-start=\"2600\" data-easing=\"easeOutExpo\"><a href=\"http://hogash.com/themeforest/?theme=ammon_joomla\">VIEW ONLINE</a> / <a href=\"http://themeforest.net/item/ammon-jomsocial-ready-template-for-joomla/669895?ref=hogash\">MORE DETAILS</a></div>\n"
				"                              \n"
				"                              <div class=\"caption lfr\" data-x=\"250\" data-y=\"180\" data-speed=\"600\" data-start=\"1200\" data-easing=\"easeOutExpo\"><img src=\"images/sliders/portfolio_devices/slide1/monitor.png\" alt=\"\"></div>\n"
				"                              <div class=\"caption lfr\" data-x=\"120\" data-y=\"310\" data-speed=\"600\" data-start=\"1400\" data-easing=\"easeOutExpo\"><img src=\"images/sliders/portfolio_devices/slide1/ipad.png\" alt=\"\"></div>\n"
				"                              <div class=\"caption lfr\" data-x=\"560\" data-y=\"350\" data-speed=\"600\" data-start=\"1600\" data-easing=\"easeOutExpo\"><img src=\"images/sliders/portfolio_devices/slide1/macbook.png\" alt=\"\"></div>\n"
				"                              <div class=\"caption lfr\" data-x=\"290\" data-y=\"425\" data-speed=\"600\" data-start=\"1800\" data-easing=\"easeOutExpo\"><img src=\"images/sliders/portfolio_devices/slide1/iphone.png\" alt=\"\"></div>\n"
				"                              \n"
				"                              <div class=\"caption lfb project_subtitle\" data-x=\"235\" data-y=\"560\" data-speed=\"300\" data-start=\"1000\" data-easing=\"easeOutExpo\">ULTRA-PREMIUM CREATIVE TEMPLATE FOR JOOMLA</div>\n"
				"                          </li>\n"
				"                          \n"
				"                          <li data-transition=\"slideright\">\n"
				"                              <img src=\"images/sliders/portfolio_devices/slide2/bg.jpg\" alt=\"\">\n"
				"                              \n"
				"                              <div class=\"caption lft project_title\" data-x=\"300\" data-y=\"120\" data-speed=\"300\" data-start=\"700\" data-easing=\"easeOutExpo\">EKHO Template</div>\n"
				"                              <div class=\"caption lft more_details\" data-x=\"410\" data-y=\"155\" data-speed=\"300\" data-start=\"2600\" data-easing=\"easeOutExpo\"><a href=\"http://hogash.com/themeforest/?theme=ekho_joomla\">VIEW ONLINE</a> / <a href=\"http://themeforest.net/item/ekho-unique-joomla-template/2544064?ref=hogash\">MORE DETAILS</a></div>\n"
				"                              \n"
				"                              <div class=\"caption lfl\" data-x=\"250\" data-y=\"180\" data-speed=\"600\" data-start=\"1200\" data-easing=\"easeOutExpo\"><img src=\"images/sliders/portfolio_devices/slide2/monitor.png\" alt=\"\"></div>\n"
				"                              <div class=\"caption lfl\" data-x=\"120\" data-y=\"310\" data-speed=\"600\" data-start=\"1400\" data-easing=\"easeOutExpo\"><img src=\"images/sliders/portfolio_devices/slide2/ipad.png\" alt=\"\"></div>\n"
				"                              <div class=\"caption lfl\" data-x=\"560\" data-y=\"350\" data-speed=\"600\" data-start=\"1600\" data-easing=\"easeOutExpo\"><img src=\"images/sliders/portfolio_devices/slide2/macbook.png\" alt=\"\"></div>\n"
				"                              <div class=\"caption lfl\" data-x=\"290\" data-y=\"425\" data-speed=\"600\" data-start=\"1800\" data-easing=\"easeOutExpo\"><img src=\"images/sliders/portfolio_devices/slide2/iphone.png\" alt=\"\"></div>\n"
				"                              \n"
				"                              <div class=\"caption lfb project_subtitle\" data-x=\"245\" data-y=\"560\" data-speed=\"300\" data-start=\"1000\" data-easing=\"easeOutExpo\">UNIQUE FULLSCREEN TEMPLATE FOR JOOMLA</div>";
			#line 452 "main_layout.tmpl"
			out()<<cppcms::filters::escape(content.text);
			#line 1185 "main_layout.tmpl"
			out()<<" World!</h1>\n"
				"                          </li>\n"
				"                          \n"
				"                          <li data-transition=\"slideright\">\n"
				"                              <img src=\"images/sliders/portfolio_devices/slide3/bg.jpg\" alt=\"\">\n"
				"                              \n"
				"                              <div class=\"caption lft project_title\" data-x=\"324\" data-y=\"120\" data-speed=\"300\" data-start=\"700\" data-easing=\"easeOutExpo\">EOS Template</div>\n"
				"                              <div class=\"caption lft more_details\" data-x=\"410\" data-y=\"155\" data-speed=\"300\" data-start=\"2600\" data-easing=\"easeOutExpo\"><a href=\"http://hogash.com/themeforest/?theme=eos_joomla\">VIEW ONLINE</a> / <a href=\"http://themeforest.net/item/eos-jomsocial-ready-template-for-joomla/1192184?ref=hogash\">MORE DETAILS</a></div>\n"
				"                              \n"
				"                              <div class=\"caption lfr\" data-x=\"250\" data-y=\"190\" data-speed=\"600\" data-start=\"1200\" data-easing=\"easeOutExpo\"><img src=\"images/sliders/portfolio_devices/slide3/monitor.png\" alt=\"\"></div>\n"
				"                              <div class=\"caption lfr\" data-x=\"120\" data-y=\"310\" data-speed=\"600\" data-start=\"1400\" data-easing=\"easeOutExpo\"><img src=\"images/sliders/portfolio_devices/slide3/ipad.png\" alt=\"\"></div>\n"
				"                              <div class=\"caption lfr\" data-x=\"560\" data-y=\"350\" data-speed=\"600\" data-start=\"1600\" data-easing=\"easeOutExpo\"><img src=\"images/sliders/portfolio_devices/slide3/macbook.png\" alt=\"\"></div>\n"
				"                              <div class=\"caption lfr\" data-x=\"290\" data-y=\"425\" data-speed=\"600\" data-start=\"1800\" data-easing=\"easeOutExpo\"><img src=\"images/sliders/portfolio_devices/slide3/iphone.png\" alt=\"\"></div>\n"
				"                              \n"
				"                              <div class=\"caption lfb project_subtitle\" data-x=\"235\" data-y=\"560\" data-speed=\"300\" data-start=\"1000\" data-easing=\"easeOutExpo\">AWESOME AND CREATIVE TEMPLATE FOR JOOMLA</div>\n"
				"                          </li>\n"
				"\n"
				"                          <li data-transition=\"slideright\">\n"
				"                              <img src=\"images/sliders/portfolio_devices/slide4/slide4.jpg\" alt=\"\">\n"
				"                              \n"
				"                              <div class=\"caption lft project_title\" data-x=\"364\" data-y=\"150\" data-speed=\"300\" data-start=\"700\" data-easing=\"easeOutExpo\">AND MANY OTHERS</div>\n"
				"                              <div class=\"caption lft more_details\" data-x=\"450\" data-y=\"185\" data-speed=\"300\" data-start=\"2600\" data-easing=\"easeOutExpo\"><a href=\"http://themeforest.net/user/hogash/portfolio?ref=hogash\">CHECK OUT MY PORTFOLIO</a></div>\n"
				"                              \n"
				"                              <div class=\"caption lfr\" data-x=\"530\" data-y=\"285\" data-speed=\"600\" data-start=\"1200\" data-easing=\"easeOutExpo\"><img src=\"images/sliders/portfolio_devices/slide4/frame4.png\" alt=\"\"></div>\n"
				"                              <div class=\"caption lfr\" data-x=\"375\" data-y=\"280\" data-speed=\"600\" data-start=\"1400\" data-easing=\"easeOutExpo\"><img src=\"images/sliders/portfolio_devices/slide4/frame3.png\" alt=\"\"></div>\n"
				"                              <div class=\"caption lfr\" data-x=\"230\" data-y=\"260\" data-speed=\"600\" data-start=\"1600\" data-easing=\"easeOutExpo\"><img src=\"images/sliders/portfolio_devices/slide4/frame2.png\" alt=\"\"></div>\n"
				"                              <div class=\"caption lfr\" data-x=\"0\" data-y=\"225\" data-speed=\"600\" data-start=\"1800\" data-easing=\"easeOutExpo\"><img src=\"images/sliders/portfolio_devices/slide4/frame1.png\" alt=\"\"></div>\n"
				"                          </li>\n"
				"                          \n"
				"                      </ul>\n"
				"                      <div class=\"tp-bannertimer\"></div> \n"
				"                  </div><!-- end fullwidthbanner -->\n"
				"              </div>\n"
				"                  \n"
				"          </div><!-- end slideshow -->\n"
				"          \n"
				"          \n"
				"      <section id=\"content\">\n"
				"        <div class=\"container\">\n"
				"        \n"
				"          <div class=\"row image-boxes imgboxes_style1\">\n"
				"                      <div class=\"span4 box\">\n"
				"              <a href=\"#\" class=\"hoverBorder\">\n"
				"                <img src=\"images/site_images/img1.jpg\" alt=\"\">\n"
				"                <h6>Read more +</h6>\n"
				"              </a>\n"
				"                          <h3 class=\"m_title\">MULTIPURPOSE TEMPLATE</h3>\n"
				"                          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod.</p>\n"
				"                      </div><!-- end span -->\n"
				"            \n"
				"            <div class=\"span4 box\">\n"
				"              <a href=\"#\" class=\"hoverBorder\">\n"
				"                <img src=\"images/site_images/img2.jpg\" alt=\"\">\n"
				"                <h6>Read more +</h6>\n"
				"              </a>\n"
				"                          <h3 class=\"m_title\">WELL DOCUMENTED</h3>\n"
				"                          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod.</p>\n"
				"                      </div><!-- end span -->\n"
				"            \n"
				"            <div class=\"span4 box\">\n"
				"              <a href=\"#\" class=\"hoverBorder\">\n"
				"                <img src=\"images/site_images/img3.jpg\" alt=\"\">\n"
				"                <h6>Read more +</h6>\n"
				"              </a>\n"
				"                          <h3 class=\"m_title\">GREAT SUPPORT</h3>\n"
				"                          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod.</p>\n"
				"                      </div><!-- end span -->\n"
				"            \n"
				"                  </div><!-- end row // imgboxes_style1 -->\n"
				"          \n"
				"                  <div class=\"row services_box\">\n"
				"            <div class=\"span4\">\n"
				"              <div class=\"box fixclear\">\n"
				"                <div class=\"icon\"><img src=\"images/icons/services_box/ico-01.png\" alt=\"\"></div>\n"
				"                <h4 class=\"title\">WEB DESIGN  SERVICES</h4>\n"
				"                <ul class=\"list-style1\">\n"
				"                  <li>Content management systens</li>\n"
				"                  <li>Virtual shops and ecommerce </li>\n"
				"                  <li>Presentation websites</li>\n"
				"                  <li>Online catalogues</li>\n"
				"                  <li>Portal systems</li>\n"
				"                  <li>& any other dynamic website </li>\n"
				"                </ul>\n"
				"              </div><!-- end box -->\n"
				"            </div>\n"
				"            <div class=\"span4\">\n"
				"              <div class=\"box fixclear\">\n"
				"                <div class=\"icon\"><img src=\"images/icons/services_box/ico-02.png\" alt=\"\"></div>\n"
				"                <h4 class=\"title\">GRAPHIC DESIGN SERVICES</h4>\n"
				"                <ul class=\"list-style1\">\n"
				"                  <li>Logo design</li>\n"
				"                  <li>Flyers & Brochures</li>\n"
				"                  <li>Business Cards</li>\n"
				"                  <li>Stationery Design</li>\n"
				"                  <li>Powerpoint presentation</li>\n"
				"                  <li>Print Ads / Magazine</li>\n"
				"                  <li>Banners</li>\n"
				"                </ul>\n"
				"              </div><!-- end box -->\n"
				"            </div>\n"
				"            <div class=\"span4\">\n"
				"              <div class=\"box fixclear\">\n"
				"                <div class=\"icon\"><img src=\"images/icons/services_box/ico-03.png\" alt=\"\"></div>\n"
				"                <h4 class=\"title\">INTERNET MARKETING</h4>\n"
				"                <ul class=\"list-style1\">\n"
				"                  <li>Search engine optimisation</li>\n"
				"                  <li>Search engine marketing</li>\n"
				"                  <li>Internet advertising</li>\n"
				"                  <li>Web analysis</li>\n"
				"                  <li>Blog marketing</li>\n"
				"                </ul>\n"
				"              </div><!-- end box -->\n"
				"            </div>\n"
				"          </div><!-- end row // services_box -->\n"
				"          \n"
				"          \n"
				"          <div class=\"row recentwork_carousel default-style\">\n"
				"            <div class=\"span3\">\n"
				"              <h3 class=\"m_title\">RECENT WORKS</h3>\n"
				"              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.</p>\n"
				"              <div class=\"controls\">\n"
				"                <a href=\"#\" class=\"prev\"><span class=\"icon-chevron-left\"></span></a>\n"
				"                <a href=\"#\" class=\"complete\"><span class=\"icon-th\"></span></a>\n"
				"                <a href=\"#\" class=\"next\"><span class=\"icon-chevron-right\"></span></a>\n"
				"              </div>\n"
				"            </div>\n"
				"            <div class=\"span9\">\n"
				"              <ul id=\"recent_works1\" class=\"fixclear\">\n"
				"                <li>\n"
				"                  <a href=\"#\">\n"
				"                    <span class=\"hover\">\n"
				"                      <img src=\"images/site_images/recent_works/work1.jpg\" alt=\"\" />\n"
				"                      <span class=\"hov\"></span>\n"
				"                    </span>\n"
				"                    <div class=\"details\">\n"
				"                      <span class=\"bg\"></span>\n"
				"                      <h4>Business cards project</h4>\n"
				"                      <span>Graphic Design</span>\n"
				"                    </div>\n"
				"                  </a>\n"
				"                </li><!-- end item -->\n"
				"                <li>\n"
				"                  <a href=\"#\">\n"
				"                    <span class=\"hover\">\n"
				"                      <img src=\"images/site_images/recent_works/work2.jpg\" alt=\"\" />\n"
				"                      <span class=\"hov\"></span>\n"
				"                    </span>\n"
				"                    <div class=\"details\">\n"
				"                      <span class=\"bg\"></span>\n"
				"                      <h4>Business cards project</h4>\n"
				"                      <span>Graphic Design</span>\n"
				"                    </div>\n"
				"                  </a>\n"
				"                </li><!-- end item -->\n"
				"                <li>\n"
				"                  <a href=\"#\">\n"
				"                    <span class=\"hover\">\n"
				"                      <img src=\"images/site_images/recent_works/work3.jpg\" alt=\"\" />\n"
				"                      <span class=\"hov\"></span>\n"
				"                    </span>\n"
				"                    <div class=\"details\">\n"
				"                      <span class=\"bg\"></span>\n"
				"                      <h4>Business cards project</h4>\n"
				"                      <span>Graphic Design</span>\n"
				"                    </div>\n"
				"                  </a>\n"
				"                </li><!-- end item -->\n"
				"                <li>\n"
				"                  <a href=\"#\">\n"
				"                    <span class=\"hover\">\n"
				"                      <img src=\"images/site_images/recent_works/work4.jpg\" alt=\"\" />\n"
				"                      <span class=\"hov\"></span>\n"
				"                    </span>\n"
				"                    <div class=\"details\">\n"
				"                      <span class=\"bg\"></span>\n"
				"                      <h4>Business cards project</h4>\n"
				"                      <span>Graphic Design</span>\n"
				"                    </div>\n"
				"                  </a>\n"
				"                </li><!-- end item -->\n"
				"              </ul>\n"
				"            </div>\n"
				"          </div><!-- end row // recentworks_carousel default-style -->\n"
				"          \n"
				"          <div class=\"row\">\n"
				"            <div class=\"span10\">\n"
				"              <h3 class=\"m_title\" style=\"margin-top:25px;\">KALLYAS Template IS AN ALL IN ONE PRODUCT WITH LOTS OF  GOODIES AND FEATURES, BASED ON OWN FRAMEWORK</h3>\n"
				"              <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium</p>\n"
				"            </div>\n"
				"            <div class=\"span2\">\n"
				"              <a href=\"#\" class=\"circlehover with-symbol\" data-size=\"\" data-position=\"top-left\" data-align=\"right\">\n"
				"                <span class=\"text\">FIND OUT MORE</span>\n"
				"                <span class=\"symbol\"><img src=\"images/ok.png\" alt=\"\"></span>\n"
				"              </a>\n"
				"            </div>\n"
				"          </div><!-- end row // circlehover -->\n"
				"          \n"
				"          <div class=\"row feature_box style2\">\n"
				"            <div class=\"span12\">\n"
				"              <h4 class=\"smallm_title centered bigger\"><span>WHY CHOOSE THIS THEME</span></h4>\n"
				"            </div>\n"
				"            <div class=\"span3\">\n"
				"              <div class=\"box\">\n"
				"                <span class=\"icon\"><img src=\"images/icons/featured_boxes2/ico-01.png\" alt=\"\"></span>\n"
				"                <h4 class=\"title\">CUSTOMER SUPPORT</h4>\n"
				"                <p>Great customer support! Check out our forum.</p>\n"
				"              </div>\n"
				"              <div class=\"box\">\n"
				"                <span class=\"icon\"><img src=\"images/icons/featured_boxes2/ico-05.png\" alt=\"\"></span>\n"
				"                <h4 class=\"title\">RESPONSIVE</h4>\n"
				"                <p>The template has a responsive layout. Try resizing the window.</p>\n"
				"              </div>\n"
				"            </div>\n"
				"            <div class=\"span3\">\n"
				"              <div class=\"box\">\n"
				"                <span class=\"icon\"><img src=\"images/icons/featured_boxes2/ico-02.png\" alt=\"\"></span>\n"
				"                <h4 class=\"title\">WELL DOCUMENTED</h4>\n"
				"                <p>Documentation include with explanations for most of the options.</p>\n"
				"              </div>\n"
				"              <div class=\"box\">\n"
				"                <span class=\"icon\"><img src=\"images/icons/featured_boxes2/ico-06.png\" alt=\"\"></span>\n"
				"                <h4 class=\"title\">MULTILANGUAGE READY</h4>\n"
				"                <p>You can install languages and extend the website's languages.</p>\n"
				"              </div>\n"
				"            </div>\n"
				"            <div class=\"span3\">\n"
				"              <div class=\"box\">\n"
				"                <span class=\"icon\"><img src=\"images/icons/featured_boxes2/ico-03.png\" alt=\"\"></span>\n"
				"                <h4 class=\"title\">UNLIMITED COLORS</h4>\n"
				"                <p>With just a few clicks you can add any color you want.</p>\n"
				"              </div>\n"
				"              <div class=\"box\">\n"
				"                <span class=\"icon\"><img src=\"images/icons/featured_boxes2/ico-07.png\" alt=\"\"></span>\n"
				"                <h4 class=\"title\">HTML5 &amp; CSS3</h4>\n"
				"                <p>Built with modern technologies like HTML5 and CSS3.</p>\n"
				"              </div>\n"
				"            </div>\n"
				"            <div class=\"span3\">\n"
				"              <div class=\"box\">\n"
				"                <span class=\"icon\"><img src=\"images/icons/featured_boxes2/ico-04.png\" alt=\"\"></span>\n"
				"                <h4 class=\"title\">CUSTOM SHORTCODES</h4>\n"
				"                <p>Great custom shortcodes which are ment to ease up your work.</p>\n"
				"              </div>\n"
				"              <div class=\"box\">\n"
				"                <span class=\"icon\"><img src=\"images/icons/featured_boxes2/ico-08.png\" alt=\"\"></span>\n"
				"                <h4 class=\"title\">HIGHLY CUSTOMIZABLE</h4>\n"
				"                <p>This template includes lots of customizations and combinations.</p>\n"
				"              </div>\n"
				"            </div>\n"
				"          </div><!-- end row // featurebox style2 -->\n"
				"          \n"
				"          <div class=\"row\">\n"
				"            <div class=\"span12\">\n"
				"              <div class=\"latest_posts acc-style\">\n"
				"                <h3 class=\"m_title\">LATEST POSTS</h3>\n"
				"                <a href=\"#\" class=\"viewall\">VIEW ALL -</a>\n"
				"                <div class=\"css3accordion\">\n"
				"                  <ul>\n"
				"                    <li>\n"
				"                      <div class=\"inner-acc\">\n"
				"                        <a href=\"#\" class=\"thumb hoverBorder\">\n"
				"                          <img src=\"images/site_images/img1.jpg\" alt=\"\">\n"
				"                        </a>\n"
				"                        <div class=\"content\">\n"
				"                          <em>03 October 2012 by Admin, in Entertanment</em>\n"
				"                                      <h5 class=\"m_title\">Nemo enim ipsam voluptatem quia voluptas sit aspernatur </h5>\n"
				"                          <div class=\"text\">Vivamus ut molestie nulla. Aenean vel tortor velit. Morbi quis varius tortor..</div>\n"
				"                          <a href=\"#\">READ MORE +</a>\n"
				"                        </div>\n"
				"                      </div>\n"
				"                    </li>\n"
				"            \n"
				"                    <li>\n"
				"                      <div class=\"inner-acc\">\n"
				"                        <a href=\"#\" class=\"thumb hoverBorder plus\">\n"
				"                          <img src=\"images/site_images/img2.jpg\" alt=\"\">\n"
				"                        </a>\n"
				"                        <div class=\"content\">\n"
				"                          <em>03 October 2012 by Admin, in Entertanment</em>\n"
				"                                      <h5 class=\"m_title\">Nemo enim ipsam voluptatem quia voluptas sit aspernatur </h5>\n"
				"                          <div class=\"text\">Vivamus ut molestie nulla. Aenean vel tortor velit. Morbi quis varius tortor..</div>\n"
				"                          <a href=\"#\">READ MORE +</a>\n"
				"                        </div>\n"
				"                      </div>\n"
				"                    </li>\n"
				"            \n"
				"                    <li class=\"last\">\n"
				"                      <div class=\"inner-acc\">\n"
				"                        <a href=\"#\" class=\"thumb hoverBorder plus\">\n"
				"                          <img src=\"images/site_images/img3.jpg\" alt=\"\">\n"
				"                        </a>\n"
				"                        <div class=\"content\">\n"
				"                          <em>03 October 2012 by Admin, in Entertanment</em>\n"
				"                                      <h5 class=\"m_title\">Nemo enim ipsam voluptatem quia voluptas sit aspernatur </h5>\n"
				"                          <div class=\"text\">Vivamus ut molestie nulla. Aenean vel tortor velit. Morbi quis varius tortor..</div>\n"
				"                          <a href=\"#\">READ MORE +</a>\n"
				"                        </div>\n"
				"                      </div>\n"
				"                    </li>\n"
				"                  </ul>\n"
				"                </div><!-- end CSS3 Accordion -->\n"
				"              </div><!-- end acc-style -->\n"
				"            </div>\n"
				"          </div><!-- end row // latest posts // acc-style -->\n"
				"\n"
				"        </div>\n"
				"        \n"
				"        <div class=\"gray-area\">\n"
				"          <div class=\"container\">\n"
				"            <div class=\"row\">\n"
				"            <div class=\"span7\">\n"
				"              <h3 class=\"m_title\">WELCOME TO KALLYAS Template</h3>\n"
				"              <a href=\"#\" class=\"hoverBorder pull-right\" style=\"margin-left:20px;\"><img src=\"images/site_images/img6.jpg\" alt=\"\"></a>\n"
				"              <p>Vivamus ut molestie nulla. Aenean vel tortor velit. Morbi quis varius tortor. Quisque sit amet leo purus, eget accumsan lorem.<br>\n"
				"  Curabitur fringilla ipsum id quam lacinia venenatis.</p>\n"
				"              <p>Nullam facilisis mattis lacus, ut dapibus risus congue vitae. Suspendisse potenti. </p>\n"
				"              <p>Nunc sodales dolor at justo posuere vitae pretium magna rhoncus. Sed quis velit eget diam condimentum tempus.</p>\n"
				"              <!-- end // welcome text -->\n"
				"            </div>\n"
				"            <div class=\"span5\">\n"
				"              <h3 class=\"m_title\">TEXT ACCORDION</h3>\n"
				"              <div class=\"acc-group default-style\">\n"
				"                <button data-toggle=\"collapse\" data-target=\"#acc1\" class=\"collapsed\">Vivamus ut molestie nulla. Aenean vel tortor velit.</button>\n"
				"                <div id=\"acc1\" class=\"collapse in\">\n"
				"                  <div class=\"content\">\n"
				"                    <p>Vivamus ut molestie nulla. Aenean vel tortor velit. Morbi quis varius tortor. Quisque sit amet leo purus, eget accumsan lorem.<br> Curabitur fringilla ipsum id quam lacinia venenatis. </p>\n"
				"                  </div><!-- end content -->\n"
				"                </div>\n"
				"              </div><!-- end acc group -->\n"
				"              <div class=\"acc-group default-style\">\n"
				"                <button data-toggle=\"collapse\" data-target=\"#acc2\" class=\"collapsed\">Duis aute irure dolor in reprehenderit in voluptate.</button>\n"
				"                <div id=\"acc2\" class=\"collapse in\">\n"
				"                  <div class=\"content\">\n"
				"                    <p>Vivamus ut molestie nulla. Aenean vel tortor velit. Morbi quis varius tortor. Quisque sit amet leo purus, eget accumsan lorem.<br> Curabitur fringilla ipsum id quam lacinia venenatis. </p>\n"
				"                  </div><!-- end content -->\n"
				"                </div>\n"
				"              </div><!-- end acc group -->\n"
				"              <div class=\"acc-group default-style\">\n"
				"                <button data-toggle=\"collapse\" data-target=\"#acc3\" class=\"collapsed\">Neque porro quisquam est qui dolorem.</button>\n"
				"                <div id=\"acc3\" class=\"collapse in\">\n"
				"                  <div class=\"content\">\n"
				"                    <p>Vivamus ut molestie nulla. Aenean vel tortor velit. Morbi quis varius tortor. Quisque sit amet leo purus, eget accumsan lorem.<br> Curabitur fringilla ipsum id quam lacinia venenatis. </p>\n"
				"                  </div><!-- end content -->\n"
				"                </div>\n"
				"              </div><!-- end acc group -->\n"
				"              <div class=\"acc-group default-style\">\n"
				"                <button data-toggle=\"collapse\" data-target=\"#acc4\" class=\"collapsed\">At vero eos et accusamus et iusto odio dignissimos.</button>\n"
				"                <div id=\"acc4\" class=\"collapse in\">\n"
				"                  <div class=\"content\">\n"
				"                    <p>Vivamus ut molestie nulla. Aenean vel tortor velit. Morbi quis varius tortor. Quisque sit amet leo purus, eget accumsan lorem.<br> Curabitur fringilla ipsum id quam lacinia venenatis. </p>\n"
				"                  </div><!-- end content -->\n"
				"                </div>\n"
				"              </div><!-- end acc group -->\n"
				"              <div class=\"acc-group default-style\">\n"
				"                <button data-toggle=\"collapse\" data-target=\"#acc5\" class=\"collapsed\">Curabitur fringilla ipsum id quam lacinia venenatis..</button>\n"
				"                <div id=\"acc5\" class=\"collapse in\">\n"
				"                  <div class=\"content\">\n"
				"                    <p>Vivamus ut molestie nulla. Aenean vel tortor velit. Morbi quis varius tortor. Quisque sit amet leo purus, eget accumsan lorem.<br> Curabitur fringilla ipsum id quam lacinia venenatis. </p>\n"
				"                  </div><!-- end content -->\n"
				"                </div>\n"
				"              </div><!-- end acc group -->\n"
				"              \n"
				"              <!-- end // accordion texts  -->\n"
				"            </div>\n"
				"          </div><!-- end row // welcome text // acc texts  -->\n"
				"          \n"
				"            <div class=\"row\">\n"
				"              <div class=\"span12\">\n"
				"                <!-- Attributes -->\n"
				"                <!-- data-align = left / right / top / bottom -->\n"
				"                <!-- data-size = small / medium / large / full / onethird / twothirds -->\n"
				"                <!-- data-theme = light / dark -->\n"
				"                <div class=\"testimonial_box\" data-align=\"left\" data-size=\"small\" data-theme=\"light\">\n"
				"                  <div class=\"details\">\n"
				"                    <img src=\"images/testimonial_logo.png\" alt=\"\">\n"
				"                    <h6><strong>Paul Simon</strong> General Manager</h6>\n"
				"                  </div>\n"
				"                  <blockquote>I'm very happy with your services. I have an excellent website built from scratch and I'm 100% happy.</blockquote>\n"
				"                </div><!-- end testimonial box -->\n"
				"                <div class=\"testimonial_box\" data-align=\"top\" data-size=\"large\" data-theme=\"dark\">\n"
				"                  <div class=\"details\">\n"
				"                    <img src=\"images/testimonial_logo.png\" alt=\"\">\n"
				"                    <h6><strong>Andrew Smith</strong> Strategic Coordinator</h6>\n"
				"                  </div>\n"
				"                  <blockquote>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum. Donec id elit non mi porta gravida at eget metus.</blockquote>\n"
				"                </div><!-- end testimonial box -->\n"
				"                \n"
				"                <div class=\"clear\"></div>\n"
				"              </div>\n"
				"            </div><!-- end row // testimonials -->\n"
				"          </div>\n"
				"        </div>\n"
				"        \n"
				"        <div class=\"container\">\n"
				"        \n"
				"          <div class=\"row\">\n"
				"            <div class=\"span12\">\n"
				"              <div class=\"process_steps fixclear\">\n"
				"                <div class=\"step intro\">\n"
				"                  <h3>our working process <strong>in 3 steps</strong></h3>\n"
				"                  <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi.</p>\n"
				"                  <a href=\"#\">MORE ABOUT US +</a>\n"
				"                </div><!-- end step -->\n"
				"                <div class=\"step step1\">\n"
				"                  <div class=\"icon\" data-animation=\"tada\">\n"
				"                    <img src=\"images/icons/steps/ico-plan.png\" alt=\"\">\n"
				"                  </div>\n"
				"                  <h3>planning &amp; strategy</h3>\n"
				"                  <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.</p>\n"
				"                </div><!-- end step -->\n"
				"                <div class=\"step step2\">\n"
				"                  <div class=\"icon\" data-animation=\"pulse\">\n"
				"                    <img src=\"images/icons/steps/ico-designdev.png\" alt=\"\">\n"
				"                  </div>\n"
				"                  <h3>design &amp; develop</h3>\n"
				"                  <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.</p>\n"
				"                </div><!-- end step -->\n"
				"                <div class=\"step step3\">\n"
				"                  <div class=\"icon\" data-animation=\"fadeOutRightBig\">\n"
				"                    <img src=\"images/icons/steps/ico-launch.png\" alt=\"\">\n"
				"                  </div>\n"
				"                  <h3>test &amp; deliver</h3>\n"
				"                  <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.</p>\n"
				"                </div><!-- end step -->\n"
				"              </div>\n"
				"\n"
				"            </div>\n"
				"          </div><!-- end row // process_steps -->\n"
				"          \n"
				"          <div class=\"row partners_carousel\">\n"
				"            <div class=\"span2\">\n"
				"              <h5 class=\"title\"><span>OUR PARTNERS // TEHNOLOGIES USED</span></h5>\n"
				"              <div class=\"controls\">\n"
				"                <a href=\"#\" class=\"prev\"><span class=\"icon-chevron-left\"></span></a>\n"
				"                <a href=\"#\" class=\"next\"><span class=\"icon-chevron-right\"></span></a>\n"
				"              </div>\n"
				"            </div>\n"
				"            <div class=\"span10\">\n"
				"              <ul id=\"partners_carousel\" class=\"fixclear\">\n"
				"                <li><a href=\"#\"><img src=\"images/partners/css3.png\" alt=\"\" /></a></li>\n"
				"                <li><a href=\"#\"><img src=\"images/partners/html5.png\" alt=\"\" /></a></li>\n"
				"                <li><a href=\"#\"><img src=\"images/partners/joomla.png\" alt=\"\" /></a></li>\n"
				"                <li><a href=\"#\"><img src=\"images/partners/wordpress.png\" alt=\"\" /></a></li>\n"
				"                <li><a href=\"#\"><img src=\"images/partners/themeforest.png\" alt=\"\" /></a></li>\n"
				"                <li><a href=\"#\"><img src=\"images/partners/jquery.png\" alt=\"\" /></a></li>\n"
				"              </ul>\n"
				"            </div>\n"
				"          </div><!-- end row // partners carousel -->\n"
				"          \n"
				"          <div class=\"row\">\n"
				"            <div class=\"span12\">\n"
				"              <div class=\"keywordbox\">just some keywords here, services or what any text you want</div>\n"
				"            </div>\n"
				"          </div><!-- end row // keywords-->\n"
				"          \n"
				"        </div><!-- end container -->\n"
				"      </section><!-- end #content -->\n"
				"          \n"
				"  <footer id=\"footer\">\n"
				"    <div class=\"container\">\n"
				"      <div class=\"row\">\n"
				"        <div class=\"span5\">\n"
				"          <h3 class=\"m_title\">FOOTER MENU</h3>\n"
				"          <ul class=\"menu\">\n"
				"            <li><a href=\"#\">Curabitur iaculis</a></li>\n"
				"            <li><a href=\"#\">Parturient montes</a></li>\n"
				"            <li><a href=\"#\">Vulputate magna</a></li>\n"
				"            <li><a href=\"#\">Cum sociis natoque</a></li>\n"
				"            <li><a href=\"#\">Nulla varius commodo</a></li>\n"
				"            <li><a href=\"#\">Parturient montes</a></li>\n"
				"            <li><a href=\"#\">Vulputate magna</a></li>\n"
				"            <li><a href=\"#\">Cum sociis natoque</a></li>\n"
				"            <li><a href=\"#\">Nulla varius commodo</a></li>\n"
				"          </ul><!-- end footer menu -->\n"
				"        </div>\n"
				"        <div class=\"span4\">\n"
				"          <div class=\"newsletter-signup\">\n"
				"            <h3 class=\"m_title\">NEWSLETTER SIGNUP</h3>\n"
				"            <p>By subscribing to our mailing list you will always be update with the latest news from us.</p>\n"
				"            <form method=\"post\" id=\"newsletter_subscribe\" name=\"newsletter_form\">\n"
				"              <input type=\"text\" name=\"nl-email\" id=\"nl-email\" value=\"\" placeholder=\"your.address@email.com\" />\n"
				"              <input type=\"submit\" name=\"submit\" id=\"nl-submit\" value=\"JOIN US\" />\n"
				"            </form>\n"
				"            <span id=\"result\">* it really works! Mailchimp Integration.</span>\n"
				"            <p><small>We never spam!</small></p>\n"
				"          </div><!-- end newsletter-signup -->\n"
				"        </div>\n"
				"        <div class=\"span3\">\n"
				"          <div class=\"contact-details\">\n"
				"            <h3 class=\"m_title\">GET IN TOUCH</h3>\n"
				"            <p><strong>T (212) 555 55 00</strong><br />\n"
				"            Email: <a href=\"#\">sales@yourwebsite.com</a></p>\n"
				"            <p>Your Company LTD<br />\n"
				"            Street nr 100, 4536534, Chicago, US</p>\n"
				"            <p><a href=\"http://goo.gl/maps/1OhOu\" target=\"_blank\" class=\"map-link\"><span class=\"icon-map-marker icon-white\"></span> Open in Google Maps</a></p>\n"
				"          </div><!-- end contact-details -->\n"
				"        </div>\n"
				"      </div><!-- end row -->\n"
				"      \n"
				"      <div class=\"row\">\n"
				"        <div class=\"span6\">\n"
				"          <div class=\"twitter-feed\">\n"
				"          \n"
				"            <!-- twitter feeds -->\n"
				"            <div class=\"tweets\" id=\"twitterFeed\"><small>Please wait whilst our latest tweets load</small></div>\n"
				"            <a href=\"https://twitter.com/hogash\" class=\"twitter-follow-button\" data-show-count=\"false\">Follow @hogash</a><!-- follow button -->\n"
				"            \n"
				"\n"
				"          </div><!-- end twitter-feed -->\n"
				"        </div>\n"
				"        <div class=\"span6\">\n"
				"          <ul class=\"social-share fixclear\">\n"
				"            <li class=\"sc-facebook\">\n"
				"              \n"
				"              <div class=\"fb-like\" data-href=\"http://facebook.com/hogash.themeforest\" data-send=\"false\" data-layout=\"button_count\" data-width=\"120\" data-show-faces=\"false\" data-font=\"lucida grande\"></div>\n"
				"            </li><!-- facebook like -->\n"
				"            <li class=\"sc-twitter\">\n"
				"              <a href=\"https://twitter.com/share\" class=\"twitter-share-button\" data-text=\"Check out this awesome template KALLYAS\" data-via=\"hogash\" data-hashtags=\"template\">Tweet</a>\n"
				"            </li><!-- tweet button -->\n"
				"            <li class=\"sc-gplus\">\n"
				"              <script type=\"text/javascript\">\n"
				"              (function() {\n"
				"              var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;\n"
				"              po.src = 'https://apis.google.com/js/plusone.js';\n"
				"              var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);\n"
				"              })();\n"
				"              </script>\n"
				"              <div class=\"g-plusone\" data-size=\"medium\"></div>\n"
				"            </li><!-- Gogle Plus Button -->\n"
				"            <li class=\"sc-pinterest\">\n"
				"              <a href=\"http://pinterest.com/pin/create/button/?url=http%3A%2F%2Fhogash.com%2Fdemo%2Fkalypso_html%2F&amp;media=http%3A%2F%2Fhogash.com%2Fdemo%2Fkalypso_html%2Fimages%2Fsite_images%2Fscr-carousel%2Fimg2.jpg&amp;description=Kallyas%20Template\" class=\"pin-it-button\" count-layout=\"horizontal\"><img src=\"http://assets.pinterest.com/images/PinExt.png\" title=\"Pin It\" alt=\"Pin It\" /></a>\n"
				"              <script type=\"text/javascript\" src=\"//assets.pinterest.com/js/pinit.js\"></script>\n"
				"              <!-- generate yours at: http://pinterest.com/about/goodies/ -->\n"
				"            </li><!-- Pin IT Button -->\n"
				"          </ul>\n"
				"          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=\"http://platform.twitter.com/widgets.js\";fjs.parentNode.insertBefore(js,fjs);}}(document,\"script\",\"twitter-wjs\");</script><!-- twitter script -->\n"
				"        </div>\n"
				"      </div><!-- end row -->\n"
				"      \n"
				"      <div class=\"row\">\n"
				"        <div class=\"span12\">\n"
				"          <div class=\"bottom fixclear\">\n"
				"            <ul class=\"social-icons fixclear\">\n"
				"              <li class=\"title\">GET SOCIAL</li>\n"
				"              <li class=\"social-twitter\"><a href=\"#\">Twitter</a></li>\n"
				"              <li class=\"social-dribbble\"><a href=\"#\">Dribbble</a></li>\n"
				"              <li class=\"social-facebook\"><a href=\"#\">Facebook</a></li>\n"
				"              <li class=\"social-envato\"><a href=\"#\">Envato</a></li>\n"
				"            </ul><!-- end social-icons -->\n"
				"            <div class=\"copyright\">\n"
				"              <a href=\"index.html\"><img src=\"images/logo2.png\" alt=\"\" /></a>\n"
				"              <p>&copy; 2012 <strong>KALLYAS Template</strong>. All Rights Reserved. Click <a href=\"#\">here</a> to buy it.<br />\n"
				"              Designed by <a href=\"http://www.hogash.com/\" target=\"_blank\">HOGASH</a></p>\n"
				"            </div><!-- end copyright -->\n"
				"          </div><!-- end bottom -->\n"
				"        </div>\n"
				"      </div><!-- end row -->\n"
				"      \n"
				"    </div>\n"
				"  </footer>\n"
				"          \n"
				"      </div><!-- end page_wrapper -->\n"
				"    \n"
				"      <a href=\"#\" id=\"totop\">TOP</a>\n"
				"\n"
				"  <!--////////////////// Load JS Files -->\n"
				"\n"
				"  <!-- load revolution slider scripts -->\n"
				"\n"
				"  <script type=\"text/javascript\" src=\"sliders/revolution_slider/js/jquery.themepunch.plugins.min.js\"></script>\n"
				"  <script type=\"text/javascript\" src=\"sliders/revolution_slider/js/jquery.themepunch.revolution.min.js\"></script>\n"
				"  <script type=\"text/javascript\">\n"
				"  var tpj=jQuery;\n"
				"  tpj.noConflict();\n"
				"\n"
				"  tpj(document).ready(function() {\n"
				"\n"
				"  if (tpj.fn.cssOriginal!=undefined)\n"
				"    tpj.fn.css = tpj.fn.cssOriginal;\n"
				"\n"
				"    tpj('.fullwidthbanner').revolution(\n"
				"      {\n"
				"        delay:9000,\n"
				"        startwidth:890,\n"
				"        startheight:600,\n"
				"\n"
				"        onHoverStop:\"on\",            // Stop Banner Timet at Hover on Slide on/off\n"
				"\n"
				"        thumbWidth:100,              // Thumb With and Height and Amount (only if navigation Tyope set to thumb !)\n"
				"        thumbHeight:50,\n"
				"        thumbAmount:3,\n"
				"\n"
				"        hideThumbs:200,\n"
				"        navigationType:\"bullet\",          //bullet, thumb, none, both   (No Shadow in Fullwidth Version !)\n"
				"        navigationArrows:\"verticalcentered\",    //nexttobullets, verticalcentered, none\n"
				"\n"
				"        touchenabled:\"on\",            // Enable Swipe Function : on/off\n"
				"\n"
				"        navOffsetHorizontal:0,\n"
				"        navOffsetVertical:20,\n"
				"\n"
				"        stopAtSlide:-1,              // Stop Timer if Slide \"x\" has been Reached. If stopAfterLoops set to 0, then it stops already in the first Loop at slide X which defined. -1 means do not stop at any slide. stopAfterLoops has no sinn in this case.\n"
				"        stopAfterLoops:-1,            // Stop Timer if All slides has been played \"x\" times. IT will stop at THe slide which is defined via stopAtSlide:x, if set to -1 slide never stop automatic\n"
				"\n"
				"\n"
				"\n"
				"        fullWidth:\"on\",\n"
				"\n"
				"        shadow:0                //0 = no Shadow, 1,2,3 = 3 Different Art of Shadows -  (No Shadow in Fullwidth Version !)\n"
				"\n"
				"      });\n"
				"\n"
				"\n"
				"\n"
				"\n"
				"  });\n"
				"  </script>\n"
				"  <!-- end revolution slider scripts -->\n"
				"\n"
				"  <!-- Carousels (by CarouFredSel) -->\n"
				"  <script src=\"js/jquery.carouFredSel.js\" type=\"text/javascript\"></script>\n"
				"  <script type=\"text/javascript\">\n"
				"  ;(function($) {\n"
				"    // ** partners carousel\n"
				"    $('#partners_carousel').carouFredSel({\n"
				"      responsive: true,\n"
				"      scroll: 1,\n"
				"      auto: false,\n"
				"      items: {\n"
				"        width: 250,\n"
				"        visible: {\n"
				"          min: 3,\n"
				"          max: 10\n"
				"        }\n"
				"      },\n"
				"      prev  : {  \n"
				"        button  : \".partners_carousel .prev\",\n"
				"        key    : \"left\"\n"
				"      },\n"
				"      next  : { \n"
				"        button  : \".partners_carousel .next\",\n"
				"        key    : \"right\"\n"
				"      }\n"
				"    });\n"
				"    // *** end partners carousel\n"
				"    $(window).load(function(){\n"
				"      // ** recent works\n"
				"      $('#recent_works1').carouFredSel({\n"
				"        responsive: true,\n"
				"        scroll: 1,\n"
				"        auto: false,\n"
				"        items: {\n"
				"          width: 300,\n"
				"          visible: {\n"
				"            min: 3,\n"
				"            max: 10\n"
				"          }\n"
				"        },\n"
				"        prev  : {  \n"
				"          button  : \".recentwork_carousel .prev\",\n"
				"          key    : \"left\"\n"
				"        },\n"
				"        next  : { \n"
				"          button  : \".recentwork_carousel .next\",\n"
				"          key    : \"right\"\n"
				"        }\n"
				"      });\n"
				"      // *** end recent works carousel\n"
				"    });\n"
				"  })(jQuery);\n"
				"  </script>\n"
				"  <!-- end Carousels (by CarouFredSel) -->\n"
				"\n"
				"\n"
				"  <!-- JavaScript at the bottom for fast page loading -->\n"
				"\n"
				"  <script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script><!-- Bootstrap Framework -->\n"
				"  <script type=\"text/javascript\" src=\"js/plugins.js\"></script><!-- jQuery Plugins -->\n"
				"  <script type=\"text/javascript\" src=\"addons/superfish_responsive/superfish_menu.js\"></script><!-- Superfish Menu -->\n"
				"\n"
				"\n"
				"  <script type=\"text/javascript\" src=\"js/kalypso_script.js\"></script><!-- custom scripts file -->\n"
				"\n"
				"  <!-- prettyphoto scripts & styles -->\n"
				"  <link rel=\"stylesheet\" href=\"addons/prettyphoto/prettyPhoto.css\" type=\"text/css\" />\n"
				"  <script type=\"text/javascript\" src=\"addons/prettyphoto/jquery.prettyPhoto.js\"></script>\n"
				"  <script type=\"text/javascript\">\n"
				"\n"
				"    function ppOpen(panel, width){\n"
				"      jQuery.prettyPhoto.close();\n"
				"      setTimeout(function() {\n"
				"        jQuery.fn.prettyPhoto({social_tools: false, deeplinking: false, show_title: false, default_width: width, theme:'pp_kalypso'});\n"
				"        jQuery.prettyPhoto.open(panel);\n"
				"      }, 300);\n"
				"    } // function to open different panel within the panel\n"
				"    \n"
				"    jQuery(document).ready(function($) {\n"
				"      jQuery(\"a[data-rel^='prettyPhoto'], .prettyphoto_link\").prettyPhoto({theme:'pp_kalypso',social_tools:false, deeplinking:false});\n"
				"      jQuery(\"a[rel^='prettyPhoto']\").prettyPhoto({theme:'pp_kalypso'});\n"
				"      jQuery(\"a[data-rel^='prettyPhoto[login_panel]']\").prettyPhoto({theme:'pp_kalypso', default_width:800, social_tools:false, deeplinking:false});\n"
				"      \n"
				"      jQuery(\".prettyPhoto_transparent\").click(function(e){\n"
				"        e.preventDefault();\n"
				"        jQuery.fn.prettyPhoto({social_tools: false, deeplinking: false, show_title: false, default_width: 980, theme:'pp_kalypso transparent', opacity: 0.95});\n"
				"        jQuery.prettyPhoto.open($(this).attr('href'),'','');\n"
				"      });\n"
				"      \n"
				"    });\n"
				"\n"
				"  </script>\n"
				"  <!--end prettyphoto -->\n"
				"\n"
				"  <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->\n"
				"    <script>\n"
				"      var _gaq=[[\"_setAccount\",\"UA-XXXXX-X\"],[\"_trackPageview\"]];\n"
				"      (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;\n"
				"      g.src=(\"https:\"==location.protocol?\"//ssl\":\"//www\")+\".google-analytics.com/ga.js\";\n"
				"      s.parentNode.insertBefore(g,s)}(document,\"script\"));\n"
				"    </script>\n"
				"    \n"
				"  <div class=\"hide\">\n"
				"    <div id=\"transparent_panel\" class=\"transparent_content\">\n"
				"      <p>A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.</p>\n"
				"      <p>I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now.</p>\n"
				"      <p>When, while the lovely valley teems with vapour around me, and the meridian sun strikes the upper surface of the impenetrable foliage of my trees, and but a few stray gleams steal into the inner sanctuary, I throw myself down among the tall grass by the trickling stream; and, as I lie close to the earth, a thousand unknown plants are noticed by me: when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies, then I feel the presence of the Almighty, who formed us in his own image.</p>\n"
				"      <p>Duis dictum tristique lacus, id placerat dolor lobortis sed. In nulla lorem, accumsan sed mollis eu, dapibus non sapien. Curabitur eu adipiscing ipsum. Mauris ut dui turpis, vel iaculis est. Morbi molestie fermentum sem quis ultricies. Mauris ac lacinia sapien. Fusce ut enim libero, vitae venenatis arcu. Cras viverra, libero a fringilla gravida, dolor enim cursus turpis, id sodales sem justo sit amet lectus. Fusce ut arcu eu metus lacinia commodo. Proin cursus ornare turpis, et faucibus ipsum egestas ut. Maecenas aliquam suscipit ante non consectetur. Etiam quis metus a dolor vehicula scelerisque.</p>\n"
				"      <p>Nam elementum consequat bibendum. Suspendisse id semper odio. Sed nec leo vel ligula cursus aliquet a nec nulla. Sed eu nulla quam. Etiam quis est ut sapien volutpat vulputate. Cras in purus quis sapien aliquam viverra et volutpat ligula. Vestibulum condimentum ultricies pharetra. Etiam dapibus cursus ligula quis iaculis. Mauris pellentesque dui quis mi fermentum elementum sodales libero consequat. Duis eu elit et dui varius bibendum. Sed interdum nisl in ante sollicitudin id facilisis tortor ullamcorper. Etiam scelerisque leo vel elit venenatis nec condimentum ipsum molestie. In hac habitasse platea dictumst. Sed quis nulla et nibh aliquam cursus vitae quis enim. Maecenas eget risus turpis.</p>\n"
				"    </div>\n"
				"  </div><!-- end transparent panel -->\n"
				"\n"
				"\n"
				"  </body>\n"
				"  </html>\n"
				"";
		#line 1185 "main_layout.tmpl"
		} // end of template render
	#line 1186 "main_layout.tmpl"
	}; // end of class message
#line 1187 "main_layout.tmpl"
} // end of namespace main_layout
#line 1187 "main_layout.tmpl"
namespace {
#line 1187 "main_layout.tmpl"
 cppcms::views::generator my_generator; 
#line 1187 "main_layout.tmpl"
 struct loader { 
#line 1187 "main_layout.tmpl"
  loader() { 
#line 1187 "main_layout.tmpl"
   my_generator.name("main_layout");
#line 1187 "main_layout.tmpl"
   my_generator.add_view<main_layout::message,content::message>("message",true);
#line 1187 "main_layout.tmpl"
    cppcms::views::pool::instance().add(my_generator);
#line 1187 "main_layout.tmpl"
 }
#line 1187 "main_layout.tmpl"
 ~loader() {  cppcms::views::pool::instance().remove(my_generator); }
#line 1187 "main_layout.tmpl"
} a_loader;
#line 1187 "main_layout.tmpl"
} // anon 
